pipeline:
  name: Terraform Test
  identifier: Terraform_Test
  projectIdentifier: Cassie_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: Hello world
        identifier: Hello_world
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Echo Hello World
                  identifier: Echo_Hello_World
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello inline"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
